### ISSUE TITLE
Unable to use templates from the classpath -- exception on "illegal char :"

### ISSUE THREAD

**Issue by dbelyaev** [neuland/spring-pug4j#2]
Method named `getResourceName(String name)` from `SpringTemplateLoader` class will always throw an exception whenever user is trying to define path for template loader as classpath.

In order to reproduce:

1. define `SpringTemplateLoader` as a Bean
2. use it in `PugConfiguration` initialization step
3. next try user tries to call `renderTemplate` method from pug configuration instance it will fail

initialization example:
```
    @Bean
    public SpringTemplateLoader templateLoader() {
        SpringTemplateLoader templateLoader = new SpringTemplateLoader();
        templateLoader.setTemplateLoaderPath("classpath:/templates/email");
        templateLoader.setEncoding("UTF-8");
        templateLoader.setSuffix(".pug");
        return templateLoader;
    }

    @Bean
    public PugConfiguration pugConfiguration() {
        PugConfiguration configuration = new PugConfiguration();
        configuration.setPrettyPrint(true);
        configuration.setTemplateLoader(templateLoader());
        return configuration;
    }
```

usage (that throws exception):
```
        // load template
        PugTemplate template = pugConfiguration.getTemplate("info-mail.pug");

        // render to html
        String htmlMessage = pugConfiguration.renderTemplate(template, model);
```
exception (thrown when trying to parse `classpath:/templates/email/` path via `sun.nio.fs.WindowsPathParser.normalize`):
`"Illegal char <:>"`

Am I using it wrongly or it is not possible to read templates from classpath by default? 

I see there is a `ClasspathTemplateLoader` that gives me the same issue, when I substitute `SpringTemplateLoader` with it (using `ClasspathTemplateLoader.setTemplateLoaderPath("/templates/email");`).

**Comment by dbelyaev** [comment]
@chbloemer yes, you are right -- it is on Windows machine (v10). This line throws an error:
```
				return Paths.get(templateLoaderPath).resolve(name).toString();
```

input to the method:
- `name` parameter with value `"info-mail.pug"`
- `templateLoaderPath` with value `classpath:/templates/email/`

exception details:
**type**: `InvalidPathException`
**cause**: `java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/templates/email/`
**detailMessage**: `Illegal char <:>`

**Comment by chbloemer** [comment]
Please try version 2.0.5
