### ISSUE TITLE
What should be file structure and TemplateLoaderPath? 

### ISSUE THREAD

**Issue by EmreSURK** [neuland/spring-pug4j#4]
I am getting 

I am using Spring Boot and my folder structure like that: There was an unexpected error (type=Not Found, status=404).

I put a breakpoint to return and breakpoint hit. 

```java
@Controller
public class IndexController {

    @GetMapping()
    public String greeting() {
        return "index";
    }
}
```

My file structure: 
<img width="407" alt="fileStructure" src="https://user-images.githubusercontent.com/9450430/146682490-8654dcef-f44b-4f19-aea6-cdf3cc00025f.png">

I tried these combinations but no luck.

```
 @Bean
    public SpringTemplateLoader templateLoader() {
        SpringTemplateLoader templateLoader = new SpringTemplateLoader();
        // templateLoader.setTemplateLoaderPath("/WEB-INF/");
        // templateLoader.setTemplateLoaderPath(
        // "/Users/emre/Documents/Free/SocketServer/socketserver/src/main/resources/templates/");
        //  templateLoader.setTemplateLoaderPath("/Users/emre/Documents/Free/SocketServer/socketserver/src/main/resources/templates/");
        templateLoader.setTemplateLoaderPath("/WEB-INF/resources/");

        templateLoader.setEncoding("UTF-8");
        templateLoader.setSuffix(".pug");
        return templateLoader;
    }
```

**Comment by EmreSURK** [comment]
Alright, that worked but I am not sure if it is right approach. 

`templateLoader.setTemplateLoaderPath("classpath:/templates/");`

**Comment by chbloemer** [comment]
Yes ```classpath:/templates``` is the most common approach I think nowadays. I adjusted the readme.
