### ISSUE TITLE
[release] Release of 'spring-pug4j' for the latest 'pug4j' (v2.1.0) is missing

### ISSUE THREAD

**Issue by dbelyaev** [neuland/spring-pug4j#7]
Hello, @chbloemer,

Can you, please, release new version of `spring-pug4j` that uses latest pug4j dependency [v2.1.0](https://github.com/neuland/pug4j/releases/tag/pug4j-2.1.0)?

**Comment by chbloemer** [comment]
Released with 3.1.0
